apiVersion: apps/v1 # Указывает версию API Kubernetes для работы с ресурсами типа Deployment.
kind: Deployment # Указывает, что создается ресурс типа Deployment, который управляет состоянием набора подов.
metadata: # Метаданные объекта Deployment.
  name: configmap-volume # Уникальное имя Deployment, которое используется для идентификации.
  labels: # Метки для группировки и поиска объектов. Они не обязательны, но полезны для организации.
    app.kubernetes.io/name: configmap-volume # Метка, указывающая на имя приложения.
spec: # Спецификация Deployment, описывающая его желаемое состояние.
  replicas: 3 # Количество подов (реплик), которые должны быть запущены одновременно.
  selector: # Указывает, какие поды будут управляться этим Deployment.
    matchLabels: # Список меток, которые должны совпадать с подами.
      app.kubernetes.io/name: configmap-volume # Метка для связи подов с этим Deployment.
  template: # Шаблон, описывающий создаваемые поды.
    metadata: # Метаданные, добавляемые к создаваемым подам.
      labels: # Метки, которые будут добавлены к создаваемым подам. Они должны совпадать с selector.
        app.kubernetes.io/name: configmap-volume # Метка для идентификации подов.
    spec: # Спецификация пода.
      containers: # Описание контейнеров, которые будут запущены в поде.
        - name: alpine # Имя контейнера, используемое для идентификации внутри пода.
          image: alpine:3 # Образ контейнера, который будет использован. В данном случае используется Alpine Linux версии 3.
          command: # Команда, которая будет выполняться в контейнере.
            - /bin/sh # Указывает, что будет запущен shell.
            - -c # Указывает, что shell должен выполнить следующую строку как команду.
            - while true; do echo "$(date) My preferred sport is $(cat /etc/config/sport)"; sleep 10; done; # Бесконечный цикл, который выводит текущую дату и содержимое файла `/etc/config/sport`, затем ждет 10 секунд.
          ports: # Открытые порты контейнера.
            - containerPort: 80 # Контейнер открывает порт 80, который можно использовать для связи с другими сервисами.
          volumeMounts: # Указывает, какие тома будут примонтированы к контейнеру.
            - name: config-volume # Имя тома, которое должно быть примонтировано.
              mountPath: /etc/config # Путь в контейнере, куда будет примонтирован том.
      volumes: # Описание томов, которые будут доступны поду.
        - name: config-volume # Имя тома, с которым связывается volumeMount.
          configMap: # Указывает, что том будет создан на основе ConfigMap.
            name: sport # Имя ConfigMap, который содержит данные для монтирования.
